---

- name: configure and deploy the databases
  remote_user: root
  hosts: dbservers
  roles:
    - base
    - dbservers

- name: configure and deploy the webservers
  remote_user: root
  hosts: webservers
  roles:
    - base
    - pyenv
    - webservers
  vars:
    enabled_sites:
      ericappelt:
        common_name: 'ericappelt.com'
        domains: ['ericappelt.com', 'www.ericappelt.com']
        location_services: ['animals']
