---
# Base setup for all nodes

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Ensure the selfcert group is created
  group:
    name: selfcert
    state: present
