---
# This playbook installs redis

- name: Include secret vars
  include_vars:
    file: "{{secrets_file}}"
    name: secrets
- name: Ensure redis is the latest version
  apt:
    name: redis-server
    state: present
- name: Ensure redis is running
  service:
    name: redis-server
    state: started
- name: Render redis configuration file
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: restart redis-server
